// A short, hand-maintained list rather than a full ISO-3166 dependency —
// this is a registration form field, not a shipping/tax integration.
export const COUNTRIES = [
  'Türkiye',
  'Germany',
  'United Kingdom',
  'France',
  'Italy',
  'Spain',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Austria',
  'Sweden',
  'Norway',
  'Denmark',
  'Poland',
  'Portugal',
  'Greece',
  'Russia',
  'Ukraine',
  'United States',
  'Canada',
  'United Arab Emirates',
  'Saudi Arabia',
  'Qatar',
  'Kuwait',
  'Israel',
  'Egypt',
  'China',
  'Japan',
  'South Korea',
  'India',
  'Australia',
  'Brazil',
  'Azerbaijan',
  'Georgia',
  'Other',
];
